version: '3.9'
services:
  backend:
    container_name: Tryitter_backend
    build:
      context: ./Backend/Tryitter.Web
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    restart: 'always'
    environment:
      - DOTNET_CONNECTION_STRING:@"Server=db; Database=students_db; Uid=root; Password=123456;"
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 30s
      retries: 15
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 120s
      retries: 40
    cap_add:
      - SYS_NICE